# tools/formatter.py

def format_response(raw_output: str, metadata: dict = None) -> str:
    """
    Format the final response from the model output.

    Args:
        raw_output (str): The raw string generated by the LLM.
        metadata (dict): Optional dictionary of metadata to include.

    Returns:
        str: A clean, formatted response.
    """
    # Optional: Clean up response (remove weird tokens, trim, etc.)
    cleaned = raw_output.strip()

    # Optionally attach metadata, like retrieved doc titles or warnings
    meta_section = ""
    if metadata:
        meta_lines = [f"- **{k}**: {v}" for k, v in metadata.items()]
        meta_section = "\n\n---\n\n**Metadata**\n" + "\n".join(meta_lines)

    return f"### 🧠 Soothsayer’s Response\n\n{cleaned}{meta_section}"
